# Generated by Django 3.2.4 on 2021-06-11 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='bot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.bot'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_id', models.BigIntegerField()),
                ('success', models.IntegerField()),
                ('error', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Stopped'), (1, 'Running')])),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sender')),
            ],
        ),
    ]
