# Generated by Django 3.2.4 on 2021-06-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210611_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='current_id',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sender',
            name='error',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sender',
            name='status',
            field=models.IntegerField(choices=[(0, 'Stopped'), (1, 'Running')], default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sender',
            name='success',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Runner',
        ),
    ]
