# Generated by Django 3.2.4 on 2021-06-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210611_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='current_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sender',
            name='error',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sender',
            name='status',
            field=models.IntegerField(choices=[(0, 'Stopped'), (1, 'Running')], default=0),
        ),
        migrations.AlterField(
            model_name='sender',
            name='success',
            field=models.IntegerField(default=0),
        ),
    ]
