# Generated by Django 3.2.4 on 2021-07-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210611_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='http_url',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
