# Generated by Django 3.2.4 on 2021-08-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bot_http_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='end_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
